coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 1%
        informational: true
    patch:
      default:
        target: 95%
        threshold: 1%
        informational: true
